apiVersion: apps/v1
kind: Deployment
metadata:
name: cmdlinetest
  labels:
    app: nginx
spec:
  replicas: 3      # number of pods
  Selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1     # Image version
        ports:
        - containerPort: 80
